### ISSUE TITLE
use a GUID that is not the wire display name

### ISSUE THREAD

**Issue by julialongtin** [wireapp/ldap-scim-bridge#13]
when a user changes their name, if we use GUIDs as the unique identifier (and do not display it as the display name in the ui), it should change the userName, email, and displayname appropriately.

**Comment by julialongtin** [comment]
so, this really turns out to be 'if the display name is not set, wire shows the externalID or email. please implement mapping the displayName'

**Comment by fisx** [comment]
@julialongtin fixed in #14, right?
