### ISSUE TITLE
HTTP for the scimTarget is hardcoded

### ISSUE THREAD

**Issue by aba-rechsteiner** [wireapp/ldap-scim-bridge#22]
In scimTarget the schema is hardcoded to HTTP. The scheme should be dependent on the tls parameter.

Unfortunately I don't know Haskell and therefore can't make a PR.

https://github.com/wireapp/ldap-scim-bridge/blob/78ac8df011a7f78fb5176d72ae0bbdb3a8fa6e24/src/LdapScimBridge.hs#L329

**Comment by fisx** [comment]
Definitely looks wrong, thank you for the ticket!  #23

**Comment by fisx** [comment]
Thanks again for reporting this.  This was indeed an error, and the effect was with tls:true, ldap-scim-bridge would not be able to establish a connection to the scim server available via https and simply fail.  The fix has been released on hackage and quay.io.  Please let us know if this does not (or does) solve your problem.
